### ISSUE TITLE
`NoClassDefFoundError: .../PreKeyStore` on receive after upgrading to v0.13.24

### ISSUE THREAD

**Issue by mamachanko** [AsamK/signal-cli#1919]
After upgrading to v0.13.24 from v0.13.23 messages can no longer be received. The signal-cli throws `java.lang.NoClassDefFoundError: org/signal/libsignal/protocol/state/internal/PreKeyStore`

Here's the full trace from the openclaw gateway (yes, 🙄):

```
09:20:05 error gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: Exception in thread "receive-0" java.lang.NoClassDefFoundError: org/signal/libsignal/protocol/state/internal/PreKeyStore
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:359)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.signal.libsignal.internal.Native.SessionCipher_DecryptPreKeySignalMessage(Native Method)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.signal.libsignal.protocol.SessionCipher.lambda$decrypt$1(SessionCipher.java:141)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:362)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.signal.libsignal.protocol.SessionCipher.decrypt(SessionCipher.java:134)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:278)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:230)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.whispersystems.signalservice.api.crypto.SignalSealedSessionCipher.decrypt(SignalSealedSessionCipher.java:68)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decryptInternal(SignalServiceCipher.java:212)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:145)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:147)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:222)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:106)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesContinuously(ReceiveHelper.java:77)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.asamk.signal.manager.internal.ManagerImpl.lambda$startReceiveThreadIfRequired$12(ManagerImpl.java:1329)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
09:20:05 info gateway/channels/signal {"subsystem":"gateway/channels/signal"} signal-cli: at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
```

```
$ uname -a
Linux ***** 6.8.0-52-generic #53-Ubuntu SMP PREEMPT_DYNAMIC ***** x86_64 x86_64 x86_64 GNU/Linux
```

Downgrading to v0.13.24 addresses the issue.

**Comment by AsamK** [comment]
Which build are you using? Might be a using the wrong libsignal-client version.

**Comment by mamachanko** [comment]
> Which build are you using? Might be a using the wrong libsignal-client version.

`signal-cli-0.13.24-Linux-native.tar.gz`

**Comment by AsamK** [comment]
Thanks, it was a missing jni entry in the graalvm config. I've uploaded a new build that should fix this issue: https://github.com/AsamK/signal-cli/releases/download/v0.13.24/signal-cli-0.13.24-Linux-native.tar.gz

**Comment by mamachanko** [comment]
> Thanks, it was a missing jni entry in the graalvm config. I've uploaded a new build that should fix this issue: https://github.com/AsamK/signal-cli/releases/download/v0.13.24/signal-cli-0.13.24-Linux-native.tar.gz

Thanks! Works.
