### ISSUE TITLE
UploadTooLargeException when trying to send a message

### ISSUE THREAD

**Issue by shipped-it** [AsamK/signal-cli#2032]
Hi all. signal-cli used to work well in daemon mode for me. After updating from v0.14.1 to 0.14.3, I get this issue when trying to send messages:

```
$ signal-cli send [uuid] -m "test message"
java.lang.NoClassDefFoundError: org/signal/libsignal/net/UploadTooLargeException
        at org.asamk.signal.manager.internal.SignalDependencies.lambda$getMessageSender$1(SignalDependencies.java:331)
        at org.asamk.signal.manager.internal.SignalDependencies.getOrCreate(SignalDependencies.java:391)
        at org.asamk.signal.manager.internal.SignalDependencies.getMessageSender(SignalDependencies.java:330)
        at org.asamk.signal.manager.helper.SendHelper.handleSendMessage(SendHelper.java:769)
        at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:745)
        at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:107)
        at org.asamk.signal.manager.internal.ManagerImpl.sendMessage(ManagerImpl.java:707)
        at org.asamk.signal.manager.internal.ManagerImpl.sendMessage(ManagerImpl.java:814)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:264)
        at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:37)
        at org.asamk.signal.App.handleLocalCommand(App.java:281)
        at org.asamk.signal.App.handleCommand(App.java:182)
        at org.asamk.signal.App.init(App.java:147)
        at org.asamk.signal.Main.main(Main.java:57)
Caused by: java.lang.ClassNotFoundException: org.signal.libsignal.net.UploadTooLargeException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
        ... 14 more
```

Is this a regression or another issue?

**Comment by AsamK** [comment]
`NoClassDefFoundError` means your using an incompatible libsignal library. Where did you get you signal-cli binary from?

**Comment by shipped-it** [comment]
> `NoClassDefFoundError` means your using an incompatible libsignal library. Where did you get you signal-cli binary from?

Sorry for the late reply. At the time of this issue, I got it from https://aur.archlinux.org/packages/signal-cli which builds it directly from source.

I cannot reproduce the bug, so I'm closing this for now.
